# Generated by Django 2.2.28 on 2024-03-01 15:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(default='defaultprofile.png', upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(db_index=True, max_length=128)),
                ('genre', models.CharField(max_length=128)),
                ('pictureId', models.CharField(max_length=32)),
                ('description', models.TextField(default='This game has no description.')),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamefolio_app.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '½'), (2, '★'), (3, '★½'), (4, '★★'), (5, '★★½'), (6, '★★★'), (7, '★★★½'), (8, '★★★★'), (9, '★★★★½'), (10, '★★★★★')])),
                ('datePosted', models.DateTimeField(default=datetime.datetime(2024, 3, 1, 15, 4, 32, 402099))),
                ('likes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamefolio_app.Author')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamefolio_app.Game')),
            ],
        ),
        migrations.CreateModel(
            name='ListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamefolio_app.Game')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamefolio_app.List')),
            ],
            options={
                'verbose_name_plural': 'List Entries',
            },
        ),
    ]
