# Generated by Django 2.2.28 on 2024-03-25 13:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamefolio_app', '0004_auto_20240303_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default='This user has no bio.'),
        ),
        migrations.AddField(
            model_name='list',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='datePosted',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 13, 55, 52, 118516)),
        ),
        migrations.AlterField(
            model_name='review',
            name='game',
            field=models.ForeignKey(db_column='game', on_delete=django.db.models.deletion.CASCADE, to='gamefolio_app.Game'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Ratings'), (1, '½'), (2, '★'), (3, '★½'), (4, '★★'), (5, '★★½'), (6, '★★★'), (7, '★★★½'), (8, '★★★★'), (9, '★★★★½'), (10, '★★★★★')]),
        ),
    ]
